name: flutter_auth_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  intl: ^0.20.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter_gen:
  integrations:
    flutter_svg: true
    image: true
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
